### ISSUE TITLE
Override "Saved Logins Form" entrypoints

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#10]
If I have the Lockbox webextension installed, and I navigate to "saved logins" (currently in about:preferences#logins AND context menu) I want engage the Lockbox management interface and not the browser.*

*If someone goes out of their way to download the extension, we assume they want to use their chosen management interface over the default the browser provides.

## Risks
* Blocked by in-tree design/work (FE prefs) *needs bugzilla number*

**Comment by 6a68** [comment]
This seems really difficult to me until we land in Firefox

**Comment by linuxwolf** [comment]
something will have to land in-tree.  The current thinking is a set of prefs need to be added, that this webextensions twiddles (via a to-be-defined webext API call/manifest key), and those two locations in-tree honor

**Comment by 6a68** [comment]
Ah, I see. It's trivially easy to flip a pref via an embedded API experiment.

If it's, flip a pref to change the UI, but both versions of the UI are in Firefox, that seems straightforward. We'll have to carefully manage the contact points between Lockbox and the desktop code, since the desktop code will evolve much more slowly, and we'll generally have multiple versions of the desktop code (say, what's in Beta vs. what's in Release) talking to a single version of the addon. We'll also need to apply Desktop-level care to the specifics of the UI, since it's comparatively slow and difficult to evolve stuff that's in-tree vs. in-addon, and will need buy-in from the relevant peers. Totally doable, but relatively slow and some potential for friction.

If the idea is to flip a pref, then have the Lockbox addon inject UI into the preferences page, that seems more difficult. Organizationally, I'd expect some resistance to the idea of changing the preferences page with code that isn't in-tree. There are also the technical issues with about page communication. This can all be done, but it seems fairly novel to me...I suspect there be dragons here.

**Comment by linuxwolf** [comment]
To be addressed as part of [bugzilla-1529729](https://bugzilla.mozilla.org/show_bug.cgi?id=1529729)
