### ISSUE TITLE
Firefox entry points to open Lockbox

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#107]
Now that we have [Bug #1529729](https://bugzilla.mozilla.org/show_bug.cgi?id=1529729), we need to ensure that all the entry points (both new and old) appropriately open the Lockbox management interface.

## Implementation

* Add a method on the `experiments.logins` API to register a URL
* Call the `experiments.logins` API to make the registration
* Update the `signon.management.overrideURL` as a default

**Comment by mnoorenberghe** [comment]
If you set the pref on the default branch then it won't persist to disk (and potentially leftover if the extension somehow gets uninstalled when the browser's not running). This is what we use for pref-flip experiments in Firefox. You can do this on every startup of the extension:
```js
Services.prefs.getDefaultBranch(null).setCharPref("signon.management.overrideURL", url);
```

You will still want to revert this on extension shutdown so that the entrypoints work to open the non-extension UI if the user uninstalls the extension.
