### ISSUE TITLE
Promote Sync on mobile Lockbox apps

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#14]
Child of #38

When I want to get my passwords across my many devices, I want to clearly know how to do that

## Acceptance criteria
* Should indicate in the password management interface that the user can download companion mobile apps
* Should not be possible (yet?) to dismiss banner
* Should open the call-to-action in a new tab/window
* "Learn More" link should be the only clickable area
* Should always display regardless of the Sync state of the user

## Implementation Details
* Should be prepared to be contextual

## Visual Design
**Zeplin**
https://zpl.io/boK9ggk
(Current approach is to link to lockbox.firefox.com page for both iOS and Android, letting the functionality built on that page handle text/email of app, as well as providing additional information to the user regarding the apps)

**Comment by sandysage** [comment]
Learn More Link still needs to be defined. We'll have a follow up story for hooking up all the "learn more" URLs.

**Comment by linuxwolf** [comment]
@mozilla-lockbox/product @mozilla-lockbox/ux Some questions:

* If the size of the tab/window means the details (or future "no entries" onboarding) would fill the entire view area, what is the preferred display (e.g., promotion overlaps metadata/password? scroll whole right-hand side?)
* If the size of the tab/window is narrow, such that content would wrap, what is the preferred handling (e.g., scroll just the promotion "banner"? scroll the whole right-hand side?)

**Comment by changecourse** [comment]
Per a conversation with @linuxwolf...

Promo area should be anchored to the base of the entry detail area, though it may be good to have a min-height in instances where the content area of entry details is not tall enough to support the total height between the meta data and the promo.

Additionally, the entire entry content area should default to scrolling on overflow, either vertically or horizontally as needed, rather than just the promo (it would look like a broken piece of iframe content otherwise)
