### ISSUE TITLE
Initial install with sync enabled, blank manage page

### ISSUE THREAD

**Issue by meandavejustice** [mozilla-lockbox/lockbox-addon#148]
When opening first opening the management interface, it displays the list of entries as expected, but a mostly blank page on the right side "details" pane.  Instead, it should display the first entry (if any).

### Steps to reproduce

1. open management page:
  - from "Lockbox" doorhanger
  - from "Logins & Passwords" in the main menu

* **Expected** The right side displays the first entry in the list from the left
* **Actual** The right side is blank (except for the promotional banner at the bottom)

## Considerations

* If the user does not have any saved logins at all, it should display the "getting started" instructional panels
* If the management interface is opened with a filter query that results in no entries, it should display the blank details pane

## Screenshot
![initial-open-lockbox](https://user-images.githubusercontent.com/1844554/56426220-797e3f00-6285-11e9-87cf-73efc4976fd6.jpg)

**Comment by SoftVision-CosminMuntean** [comment]
The issue is also reproducible in the following cases:
- If a saved login is focused and the page is refreshed. After refreshing the page the right side is blank.
- If you try to create a new entry and you click the "Cancel" button. After canceling the "Create" form, no entry is focused and the right side is blank.
