### ISSUE TITLE
Disable login prompts in Management Interface

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#57]

**Comment by linuxwolf** [comment]
Firefox may prompt the user to "save this login" while editing a login in the Lockbox management interface, which is confusing to the user and can present data storage issues (e.g., storing a loging not really intended for the hostname).

Instead, the prompts should be disabled while the management interface is the active tab.

**Comment by lmorchard** [comment]
Some notes to myself, since I think I might have finally found the relevant pieces:

* [Logic for deciding whether we can remember a login](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/nsLoginManagerPrompter.js#342)
* This logic uses [`Services.logins.getLoginSavingEnabled()`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/nsLoginManager.js#467)
* Conveniently, there also exists a [`Services.logins.setLoginsSavingEnabled()`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/nsLoginManager.js#481)
* So, I'm going to try adding these get / set methods do the logins API experiment and see if flipping that flag for our extension origin does the trick!

**Comment by linuxwolf** [comment]
_[adding to @lmorchard 's notes]_

Based on experience:

* the origin needs to be the `chrome://extension-uuid`; note the **lack** of a trailing `/`
* it can be done at any point that the extension's baseURL is known, such as when the background script first starts

**Comment by lmorchard** [comment]
Changing to WIP temporarily - I added a commit that automatically re-adds our entry to the exception list for login saving when it is somehow removed (manually or otherwise). However, this still needs unit / integration tests. However, however, this could use a sanity check as to whether this is what we actually want to do.
